<?php

	namespace JKesselring\Lorem;
	
	class Repository
	{
		private $repository = array();
		private $numberOfRecordsToReturn = 0;

		public function __construct($n) 
		{
			$this->repository = array("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempor urna est, at dignissim velit ultricies eget. Quisque fringilla dignissim enim, id consequat purus. Praesent sagittis libero nisl, sit amet pretium turpis ultrices eu. In congue venenatis rutrum. Donec sit amet convallis nunc. Nulla facilisi. Pellentesque quis felis dui. Vestibulum dictum lorem non felis imperdiet, sit amet ullamcorper tortor vulputate. Cras pharetra at arcu vitae gravida. Etiam diam lectus, commodo vel mattis ut, elementum sit amet risus. Integer felis tortor, posuere at suscipit fringilla, fringilla sit amet nunc. Fusce semper diam tempor, congue sem in, facilisis orci. Donec ac pretium massa. Nullam elementum tempor semper. Pellentesque interdum augue nec malesuada accumsan. Sed a rutrum lorem.",
					    			"Nulla lacus metus, vestibulum vitae purus semper, semper porta est. Cras et adipiscing tellus. Integer congue arcu in orci facilisis accumsan. Nulla diam lacus, placerat at sagittis quis, semper nec leo. Quisque justo nulla, feugiat quis iaculis id, volutpat sed nisi. Cras bibendum dolor ac magna luctus placerat eu sed eros. Donec aliquet est vitae lacus sollicitudin, id auctor dolor sodales. Praesent aliquam magna eu ligula facilisis egestas. Ut interdum ante nec neque rhoncus, vitae lobortis sapien fermentum. Maecenas blandit tincidunt lorem a adipiscing. Pellentesque laoreet quam et erat sollicitudin, eget bibendum risus aliquam.",
									"In consequat eget magna eget mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel imperdiet sapien. Nam ornare sed orci eget euismod. Morbi laoreet metus ac elementum aliquam. Nunc pharetra, lacus scelerisque sollicitudin blandit, eros diam tempus tortor, a faucibus leo nunc a neque. Aenean in enim ut nisl dapibus bibendum a non felis. Curabitur accumsan, ante eget molestie interdum, diam purus euismod metus, a pellentesque eros ipsum vestibulum enim. Ut diam risus, mollis et suscipit eget, faucibus eu felis. Donec eget laoreet quam. Mauris sit amet pellentesque ligula, vitae imperdiet lacus. Nulla egestas consectetur tellus, sit amet ultrices massa semper id. Vestibulum non turpis quis justo vulputate feugiat sit amet a dui. Donec lacus eros, semper et urna ut, porta aliquam orci. Phasellus feugiat placerat mauris, cursus tincidunt magna eleifend at.",
									"Sed leo sapien, tincidunt vitae arcu nec, volutpat hendrerit eros. Nam luctus tortor vitae risus adipiscing tempor at sit amet velit. Maecenas ut erat at ante aliquet mollis. Ut et faucibus quam. Donec blandit euismod mi, eu bibendum lacus fringilla et. Integer euismod leo nec lacus dapibus, in mollis sem sagittis. Nunc accumsan tortor consectetur ullamcorper pharetra. Nunc placerat suscipit ante a adipiscing. Quisque eleifend sapien non turpis tristique, quis ultrices lacus suscipit. Nulla lobortis volutpat erat. Suspendisse potenti. Nulla nibh est, tincidunt ac ultricies at, consectetur luctus turpis. Aenean non mauris mi. Sed eu ante lorem. Quisque consectetur nulla mi, in pellentesque ipsum vehicula eu. Aliquam erat volutpat.",
									"Cras augue nulla, iaculis id lorem id, viverra elementum diam. Proin et velit id eros lobortis gravida eget euismod magna. Maecenas mattis lorem mauris, et imperdiet orci pharetra sed. Cras non nunc in nulla tempor facilisis eu eu nibh. Duis faucibus magna sed nisl consectetur, id euismod elit tempor. Nulla sodales diam dolor, sed sollicitudin nisl feugiat vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eu justo ligula. Nulla facilisi. Suspendisse rutrum ac nunc eu ultrices. Mauris molestie erat et metus sollicitudin, eu volutpat diam sodales.",
									"Vestibulum facilisis sem vitae nulla mattis, ut dapibus mauris laoreet. Nam condimentum mattis purus a bibendum. Vestibulum feugiat augue eu sapien pharetra malesuada. Vivamus quam sem, feugiat et urna eu, consectetur pulvinar arcu. Aenean fringilla nisl sapien, vel tristique magna ornare quis. In a massa in ipsum lacinia posuere et sed lorem. Sed pellentesque pretium ultrices. Proin ultrices gravida mauris, sit amet porttitor ante placerat a. Pellentesque pretium, sapien quis aliquet rutrum, felis sem convallis purus, in adipiscing neque dolor eu massa. Sed iaculis, odio volutpat aliquam pretium, risus leo sollicitudin ante, nec iaculis nibh enim vel tortor. Aenean gravida ipsum ac mi feugiat, vehicula eleifend metus laoreet. Morbi volutpat ligula eros, vel scelerisque felis cursus sit amet. In eros nisi, tempus quis arcu sagittis, tempor aliquet mauris. In vel odio et diam elementum lobortis. Donec scelerisque venenatis purus, et sollicitudin elit gravida et.",
									"Nulla tincidunt ut mauris vitae luctus. Nulla vel pretium mi. Nullam rhoncus erat quis mi pretium, egestas convallis turpis tincidunt. Pellentesque varius turpis vel convallis laoreet. Sed venenatis, tellus quis placerat pellentesque, quam ipsum euismod felis, ut viverra nibh magna ac erat. In semper consectetur odio at aliquet. Maecenas rutrum, lacus sit amet elementum tincidunt, neque eros dapibus arcu, a facilisis turpis elit quis nisi. Praesent bibendum eget massa ac mattis.",
									"Nullam interdum varius lectus ut gravida. Quisque vel nisl gravida lectus laoreet consectetur sed vel lectus. Vestibulum suscipit tellus ut nulla ultricies porta. Maecenas ut massa non magna convallis venenatis. Suspendisse pulvinar enim massa, ac vehicula risus auctor non. Vestibulum pretium diam quis elementum auctor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis nec urna eu libero vehicula ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam accumsan libero a justo volutpat, in suscipit tortor commodo. Fusce tincidunt sagittis sollicitudin. Fusce fermentum nunc mauris, at rhoncus nisi ultricies sed. Maecenas et nisi nibh. Nulla molestie leo pellentesque dolor posuere iaculis. Donec aliquam libero eget tellus mollis interdum. Integer interdum aliquet nulla, vitae feugiat metus facilisis vitae.",
									"Mauris tempus sit amet eros ut ultrices. Ut condimentum varius urna, in egestas leo commodo nec. Duis cursus tincidunt consequat. Duis nec erat sagittis magna imperdiet consectetur. Aenean a ornare leo, adipiscing iaculis lacus. Quisque gravida augue eu eros tempor lobortis. Donec elit lacus, luctus id urna at, euismod varius neque. Vestibulum sit amet bibendum mi.",
									"Praesent facilisis tincidunt neque, id cursus est tincidunt at. In a odio turpis. Aliquam laoreet eget ante eget sodales. Maecenas lacinia turpis libero, vel sodales lorem accumsan at. Etiam congue dignissim sagittis. Morbi eget ornare est. Praesent adipiscing orci dui, non faucibus dui cursus et. Ut ullamcorper tempus lorem, et sollicitudin risus pulvinar vitae. Praesent sed metus malesuada, fermentum lectus id, pellentesque magna. Nam tristique, est id blandit auctor, neque libero rhoncus nibh, vel tempus quam arcu vel lacus. Vestibulum mi nulla, malesuada in elit ac, ullamcorper commodo urna. Quisque ultrices leo et metus dignissim, eu condimentum diam imperdiet. Suspendisse a massa in libero lobortis facilisis. Sed vel ante elementum, tincidunt justo ut, vestibulum libero. Sed sem risus, bibendum nec tincidunt non, consectetur vulputate sapien. Phasellus sit amet pulvinar nisi.",
									"Maecenas congue diam non est aliquet bibendum. Cras vitae justo ut sapien adipiscing dictum non eu ante. Mauris varius felis eget sapien mattis egestas. Pellentesque eu mauris id lacus imperdiet semper sed vel mauris. Ut sem orci, dapibus quis tristique id, mattis eget massa. Donec at ornare tortor. Sed mi elit, pulvinar convallis blandit nec, pulvinar et augue. Proin nec nulla non tellus rhoncus viverra ut eu justo.",
									"Fusce varius elit non laoreet posuere. Aliquam lectus nibh, dictum sit amet arcu at, pretium vestibulum sem. Vestibulum justo neque, congue vel tellus a, malesuada fermentum nisl. Suspendisse in odio pellentesque, auctor elit quis, blandit velit. Nam erat mi, blandit quis pretium in, feugiat quis nulla. Morbi gravida pulvinar felis vitae varius. Integer in dignissim quam. Integer metus leo, varius a ipsum vel, gravida auctor mi.",
									"Integer dictum, ipsum eget condimentum vulputate, urna massa varius lacus, sit amet ornare magna dolor ut purus. Quisque vehicula gravida eros quis volutpat. Maecenas ultrices lacus quis est convallis lacinia. Fusce aliquam pharetra lacus rhoncus gravida. Etiam sapien sem, rutrum ac lectus nec, luctus fermentum mauris. In at tellus sed sem condimentum aliquet non egestas felis. Praesent sollicitudin, dui quis gravida consectetur, magna dui sodales erat, vitae commodo diam nisl vel nunc.",
									"Sed malesuada tellus purus, nec convallis diam facilisis dapibus. Proin mollis eu sem pharetra dictum. Ut venenatis metus vel mi congue, in suscipit nisi laoreet. Integer mattis, enim eu elementum blandit, augue velit fermentum nisi, aliquam bibendum tellus dui sit amet elit. Suspendisse congue vitae quam id laoreet. Curabitur pellentesque nunc in imperdiet elementum. Mauris pulvinar porttitor nisl. Ut elementum pharetra mauris gravida fringilla. Donec vitae magna accumsan neque semper fringilla. Donec nec iaculis sapien, a fringilla lectus.",
									"Aenean tristique vestibulum fringilla. Vestibulum ac elit neque. Morbi et lobortis orci, quis egestas nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eleifend neque at pretium interdum. Sed in ligula molestie, ornare metus vel, scelerisque libero. Cras tempor fringilla lectus quis feugiat. Nam id neque tincidunt lectus feugiat hendrerit. Fusce fermentum eu magna in lacinia. Aliquam ornare commodo arcu ut fermentum. Nullam interdum erat tortor, quis egestas velit imperdiet id. Suspendisse at tortor id elit consequat vestibulum eu eget enim.",
									"Praesent id justo vel justo aliquam dapibus. Donec vitae mattis diam, in porttitor lorem. Cras mauris risus, vehicula ut magna eu, tempus sollicitudin tortor. Curabitur facilisis est eu porttitor sodales. Integer rutrum sapien risus, id malesuada purus tempus non. Ut enim elit, tincidunt elementum felis vel, rhoncus convallis purus. In mi risus, faucibus eu accumsan in, malesuada eu felis. Vestibulum turpis sem, posuere in semper nec, tincidunt eget eros. Maecenas non cursus felis.",
									"Nunc porttitor, est et lobortis pharetra, lorem massa luctus libero, vitae aliquam ante metus vitae odio. Vestibulum in enim sit amet ipsum gravida mollis at vel turpis. Sed tortor risus, molestie vel ante pellentesque, faucibus ultrices purus. Sed feugiat elit vulputate orci blandit, nec hendrerit augue pharetra. Vivamus suscipit eget magna ut imperdiet. Suspendisse porttitor nunc tortor, sed aliquam tellus ultricies nec. Donec ante neque, accumsan sit amet nisi ut, consequat elementum sapien. Maecenas non diam in mauris lacinia vulputate. Praesent malesuada, turpis sit amet ornare sodales, quam dui mollis nibh, eu pellentesque felis justo nec justo. Mauris dolor velit, posuere a aliquet id, cursus quis lectus. In hac habitasse platea dictumst. Nam sit amet iaculis tellus, id elementum ipsum. Fusce vitae quam non velit ultrices aliquet blandit eget massa.",
									"Curabitur congue nisl elit, eu ultrices purus pellentesque vitae. In pharetra nibh ante, sed aliquet enim pretium in. In at elit et leo tempus venenatis. Donec dapibus ante erat, quis luctus diam ornare vel. Suspendisse elementum lacinia lorem, ac scelerisque massa congue ac. Vivamus ac pharetra mi. Integer varius eros et tellus pharetra mollis at non eros. Phasellus elementum sapien pharetra nisl vestibulum aliquam. Praesent vel arcu at est lacinia ultricies. Aenean eu commodo diam, sed tincidunt arcu. Suspendisse commodo vulputate ipsum, vel rutrum justo iaculis sit amet. Donec vitae adipiscing odio, id ultricies tellus. Curabitur vel egestas arcu, non vehicula massa. Aenean eget nulla nibh. Ut scelerisque neque felis, id hendrerit justo interdum vitae. Etiam id urna eget lorem volutpat porttitor.",
									"Donec et purus quis felis hendrerit gravida. Vestibulum ac tellus ac sapien accumsan tincidunt in in tortor. In sollicitudin porttitor turpis vel laoreet. In at nunc eu ante auctor eleifend. Integer nec magna ante. Vestibulum sem ante, consectetur vitae risus ut, suscipit aliquet libero. Morbi faucibus nulla erat, in adipiscing diam tempus convallis. Mauris eget cursus mi. Morbi sit amet magna eget libero aliquam scelerisque sit amet sit amet arcu. Nam rhoncus pretium diam ut aliquam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris ac porta elit, non fermentum nunc.",
									"Etiam feugiat dapibus mi ut hendrerit. Vestibulum in ultricies massa. In convallis ullamcorper lacus, ac ultrices felis porttitor in. Suspendisse in elit vitae augue egestas porttitor. Sed dictum purus urna, ut malesuada sapien tempor a. Donec purus quam, adipiscing eget risus non, ultricies tincidunt odio. Vestibulum suscipit tempus ullamcorper. Pellentesque ac arcu sollicitudin, sodales elit id, interdum justo."
								);
			$this->numberOfRecordsToReturn = $n;
			return $this;

		}//end ctor

		public function recordCount(){
			return count($this->repository);
		}//end recordCount

		public function retrieve(){
			if($this->numberOfRecordsToReturn <= $this->recordCount()){
				return array_slice($this->repository, 0, $this->numberOfRecordsToReturn);
			}
			return $this->repository;
		}//end getRecord

	}//end Repository
	

	/* Example of Use
	$rep = new Repository();
	echo $rep->recordCount() . "<br><hr>";

	foreach ($rep->getRecord(2) as $value) {
		echo "<p>$value</p>\n\n";
	}
	
	echo "<hr>";

	foreach ($rep->getRecord(20) as $value) {
		echo "<p>$value</p>\n\n";
	}

	::To Remove::
 	*/	